<a href="https://colab.research.google.com/github/BFCC/BFCC.github.io/blob/main/taylor%26will.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import nltk
import numpy as np
import matplotlib.pyplot as plt
import random

from gensim.models import Word2Vec

from sklearn.decomposition import IncrementalPCA
from sklearn.manifold import TSNE

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
file = open("taylorvsshakes 2.csv", 'r').read()

In [4]:
for char in ["\n", "\r", "\d", "\t"]:
    file = file.replace(char, " ")

In [5]:
print(file[:100])

Text,Author "Nice to meet you, where you been?",TAYLOR I could show you incredible things,TAYLOR "Ma


In [6]:
def sample_clean_text(text: str):

    sentences = nltk.sent_tokenize(text)


    tokenized_sentences = [nltk.word_tokenize(sent) for sent in sentences]


    tokenized_text = [[word.lower() for word in sent] for sent in tokenized_sentences]


    return tokenized_text


tokens = sample_clean_text(text = file)


print(tokens[:10])

[['text', ',', 'author', '``', 'nice', 'to', 'meet', 'you', ',', 'where', 'you', 'been', '?'], ['``', ',', 'taylor', 'i', 'could', 'show', 'you', 'incredible', 'things', ',', 'taylor', '``', 'magic', ',', 'madness', ',', 'heaven', 'sin', "''", ',', 'taylor', 'saw', 'you', 'there', 'and', 'i', 'thought', ',', 'taylor', '``', 'oh', 'my', 'god', ',', 'look', 'at', 'that', 'face', "''", ',', 'taylor', 'you', 'look', 'like', 'my', 'next', 'mistake', ',', 'taylor', '``', 'love', "'s", 'a', 'game', ',', 'want', 'to', 'play', '?'], ['``', ',', 'taylor', '``', 'new', 'money', ',', 'suit', 'and', 'tie', "''", ',', 'taylor', 'i', 'can', 'read', 'you', 'like', 'a', 'magazine', ',', 'taylor', '``', 'ai', "n't", 'it', 'funny', ',', 'rumors', ',', 'lie', "''", ',', 'taylor', 'and', 'i', 'know', 'you', 'heard', 'about', 'me', ',', 'taylor', '``', 'so', 'hey', ',', 'let', "'s", 'be', 'friends', "''", ',', 'taylor', 'i', "'m", 'dying', 'to', 'see', 'how', 'this', 'one', 'ends', ',', 'taylor', 'grab', 'y

In [7]:
model = Word2Vec(tokens,vector_size=100)

In [8]:
model.wv.key_to_index

{',': 0,
 '``': 1,
 'taylor': 2,
 "''": 3,
 'shakes': 4,
 'the': 5,
 'i': 6,
 'and': 7,
 'you': 8,
 'to': 9,
 'of': 10,
 "'s": 11,
 'a': 12,
 'that': 13,
 'in': 14,
 'my': 15,
 'is': 16,
 'it': 17,
 ';': 18,
 'but': 19,
 'be': 20,
 'we': 21,
 'on': 22,
 "n't": 23,
 'me': 24,
 'love': 25,
 'do': 26,
 'like': 27,
 'shake': 28,
 'with': 29,
 'your': 30,
 'all': 31,
 '.': 32,
 'this': 33,
 'for': 34,
 'so': 35,
 'not': 36,
 '?': 37,
 "'d": 38,
 "'ll": 39,
 'as': 40,
 "'m": 41,
 "'": 42,
 'mmm': 43,
 'what': 44,
 'can': 45,
 'when': 46,
 'know': 47,
 'his': 48,
 'see': 49,
 'got': 50,
 'go': 51,
 'or': 52,
 'just': 53,
 'from': 54,
 'no': 55,
 'there': 56,
 'gon': 57,
 'na': 58,
 'say': 59,
 'he': 60,
 ':': 61,
 'make': 62,
 'which': 63,
 'up': 64,
 'out': 65,
 'take': 66,
 'thou': 67,
 'more': 68,
 'they': 69,
 'our': 70,
 'was': 71,
 'if': 72,
 'never': 73,
 'their': 74,
 "'re": 75,
 'have': 76,
 'are': 77,
 'said': 78,
 'could': 79,
 'play': 80,
 'were': 81,
 'fair': 82,
 'eyes': 83,
 'b

In [9]:
model.wv.get_vector("death", norm=True)

array([ 0.03732007,  0.14967726, -0.00601758, -0.02490525,  0.08126235,
       -0.1882974 ,  0.14207923,  0.2374641 , -0.09849568, -0.11770702,
        0.00891372, -0.21229823,  0.04152203,  0.05256933,  0.04083044,
       -0.1327475 ,  0.12131168, -0.06315383, -0.09185275, -0.27652737,
        0.05991343,  0.06557025,  0.08306471, -0.10013004,  0.01047172,
       -0.01434702, -0.1105504 ,  0.02169454, -0.1068116 , -0.04092912,
        0.10041431, -0.04990015,  0.11182851, -0.1850298 , -0.1319202 ,
        0.06711014,  0.04578491, -0.02195937,  0.02760672, -0.17083587,
        0.06924748, -0.07316588, -0.05699669, -0.01883047,  0.07726715,
       -0.03924341, -0.10877076, -0.06623753,  0.03971658,  0.06305327,
        0.00987042, -0.1204038 ,  0.03692139, -0.05199769, -0.04035149,
       -0.00264712,  0.06280641,  0.00169137, -0.09158985,  0.05827159,
        0.0639695 , -0.10219302,  0.09591613,  0.03842493, -0.03904617,
        0.18796057,  0.02721249,  0.1034448 , -0.22831947,  0.10

In [10]:
model.wv.most_similar('death')

[('``', 0.9946966767311096),
 ('taylor', 0.9945957064628601),
 ('shakes', 0.994552493095398),
 (',', 0.9945502877235413),
 ('my', 0.9945136308670044),
 ('a', 0.9944970607757568),
 ("''", 0.9943837523460388),
 ('the', 0.9943334460258484),
 ('of', 0.9942627549171448),
 ('you', 0.9941490888595581)]

In [11]:
model.wv.get_vector("love", norm=True)

array([ 0.03869933,  0.14505129, -0.00673938, -0.01762222,  0.07354008,
       -0.17575277,  0.14685652,  0.23534706, -0.10783093, -0.11470313,
        0.00172757, -0.21102771,  0.02784563,  0.05041481,  0.03290256,
       -0.14027373,  0.13312502, -0.07480015, -0.10397276, -0.29327995,
        0.04916355,  0.07043865,  0.06557265, -0.09706345, -0.00492925,
        0.00125061, -0.12142361,  0.01112762, -0.09159099, -0.02570204,
        0.11491308, -0.0427514 ,  0.08839045, -0.19190884, -0.13617896,
        0.07346626,  0.03777103, -0.02054047,  0.01936608, -0.19889972,
        0.05533275, -0.07105474, -0.04582891, -0.02469933,  0.09081151,
       -0.03020617, -0.10515442, -0.05755127,  0.03219212,  0.07153885,
        0.00192083, -0.11675661,  0.01618808, -0.05268459, -0.03519103,
       -0.00935916,  0.06021016,  0.01043542, -0.10662184,  0.05558914,
        0.07323193, -0.09001484,  0.10653879,  0.04704834, -0.04854148,
        0.18470669,  0.02150476,  0.09679823, -0.2215865 ,  0.09

In [12]:
model.wv.most_similar('love')

[(',', 0.998344361782074),
 ('i', 0.9982649683952332),
 ("''", 0.9981521964073181),
 ('taylor', 0.9981345534324646),
 ('shakes', 0.9980949759483337),
 ('``', 0.9980793595314026),
 ('that', 0.9980533719062805),
 ('the', 0.9980270266532898),
 ("'s", 0.9979459047317505),
 ('and', 0.9979361891746521)]

In [13]:
model.wv.get_vector("mmm", norm=True)

array([ 0.02743972,  0.13163498, -0.01500742, -0.02037563,  0.07647328,
       -0.18186069,  0.15050493,  0.23533241, -0.10521757, -0.12333383,
        0.01411603, -0.22555228,  0.02776257,  0.05553158,  0.03868165,
       -0.13608372,  0.12726419, -0.07851797, -0.09272287, -0.29415202,
        0.04875661,  0.06505334,  0.07254047, -0.09541202, -0.00300066,
       -0.00671285, -0.11255924,  0.01399268, -0.08725787, -0.03990055,
        0.11129236, -0.03683847,  0.10355371, -0.18709745, -0.13544007,
        0.06130896,  0.03250006, -0.02551309,  0.01204846, -0.18967839,
        0.05731816, -0.0627571 , -0.05964075, -0.02100167,  0.09645843,
       -0.02627806, -0.1043077 , -0.04602854,  0.02698823,  0.07651369,
        0.00656581, -0.11276673,  0.02566782, -0.04492257, -0.03118272,
       -0.00282771,  0.07336242,  0.00786697, -0.09278889,  0.05960841,
        0.06312086, -0.09067119,  0.10957237,  0.0477951 , -0.06519677,
        0.18018417,  0.01238544,  0.10718615, -0.20842549,  0.09

In [14]:
model.wv.most_similar('mmm')

[(',', 0.9987058043479919),
 ('``', 0.9983758926391602),
 ('of', 0.9983509182929993),
 ("''", 0.9983238577842712),
 ('you', 0.998282253742218),
 ('to', 0.9982641339302063),
 ('the', 0.9981599450111389),
 ("'s", 0.9981294870376587),
 ('a', 0.9981272220611572),
 ('and', 0.9981270432472229)]

In [15]:
model.wv.get_vector("will", norm=True)

array([ 0.04890462,  0.15061645, -0.0259628 , -0.02852299,  0.05696489,
       -0.1670265 ,  0.17009224,  0.21885936, -0.12685007, -0.12042943,
        0.00280561, -0.21551472,  0.03713944,  0.05116274,  0.05074117,
       -0.12512584,  0.11011785, -0.06996835, -0.09645201, -0.3006    ,
        0.0433888 ,  0.07914016,  0.08877099, -0.10077985, -0.01197877,
       -0.004927  , -0.11912718, -0.00465451, -0.0889166 , -0.04674909,
        0.10011875, -0.03376823,  0.08413515, -0.19102094, -0.1335842 ,
        0.08480057,  0.02181308, -0.01713104,  0.00476477, -0.17590122,
        0.07585592, -0.04731556, -0.05962211, -0.00349965,  0.10874093,
       -0.02129218, -0.11086662, -0.04698379,  0.04119139,  0.06147755,
        0.01064568, -0.10728984,  0.02530456, -0.05712559, -0.0313221 ,
        0.00603616,  0.0604454 ,  0.01664931, -0.0865401 ,  0.05792908,
        0.08264389, -0.07577629,  0.09605885,  0.05527743, -0.05140765,
        0.18372233,  0.0108276 ,  0.08985939, -0.22534844,  0.09

In [16]:
model.wv.most_similar('will')

[('and', 0.9934272170066833),
 ('the', 0.9934083223342896),
 ('i', 0.9932969808578491),
 ('that', 0.9931701421737671),
 (',', 0.9931309223175049),
 ('of', 0.9931129217147827),
 ('shakes', 0.9931001663208008),
 ('you', 0.9930810928344727),
 ("''", 0.9930498600006104),
 ('not', 0.9930294752120972)]

In [17]:
model.wv.similarity('will', 'mmm')

0.9924109

In [18]:
model.wv.similarity('will', 'love')

0.9921148

In [21]:
model.wv.similarity('will', 'taylor')

0.9928342

In [23]:
model.wv.similarity('will', 'baby')

0.9890929

In [25]:
model.wv.similarity('will', 'death')

0.98794025