<a href="https://colab.research.google.com/github/BFCC/BFCC.github.io/blob/main/TaylorvWillredux.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import nltk
import numpy as np
import matplotlib.pyplot as plt
import random

from gensim.models import Word2Vec

from sklearn.decomposition import IncrementalPCA
from sklearn.manifold import TSNE

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
file = open("taylorvsshakes 3.csv", 'r').read()

In [4]:
for char in ["\n", "\r", "\d", "\t"]:
    file = file.replace(char, " ")

In [5]:
print(file[:400])

Text,Author "Nice to meet you, where you been?",TAYLOR I could show you incredible things,TAYLOR "Magic, madness, heaven sin",TAYLOR Saw you there and I thought,TAYLOR "Oh my God, look at that face",TAYLOR You look like my next mistake,TAYLOR "Love's a game, want to play?",TAYLOR "New money, suit and tie",TAYLOR I can read you like a magazine,TAYLOR "Ain't it funny, rumors, lie",TAYLOR And I know 


In [6]:
def sample_clean_text(text: str):

    sentences = nltk.sent_tokenize(text)


    tokenized_sentences = [nltk.word_tokenize(sent) for sent in sentences]


    tokenized_text = [[word.lower() for word in sent] for sent in tokenized_sentences]


    return tokenized_text


tokens = sample_clean_text(text = file)


print(tokens[:10])

[['text', ',', 'author', '``', 'nice', 'to', 'meet', 'you', ',', 'where', 'you', 'been', '?'], ['``', ',', 'taylor', 'i', 'could', 'show', 'you', 'incredible', 'things', ',', 'taylor', '``', 'magic', ',', 'madness', ',', 'heaven', 'sin', "''", ',', 'taylor', 'saw', 'you', 'there', 'and', 'i', 'thought', ',', 'taylor', '``', 'oh', 'my', 'god', ',', 'look', 'at', 'that', 'face', "''", ',', 'taylor', 'you', 'look', 'like', 'my', 'next', 'mistake', ',', 'taylor', '``', 'love', "'s", 'a', 'game', ',', 'want', 'to', 'play', '?'], ['``', ',', 'taylor', '``', 'new', 'money', ',', 'suit', 'and', 'tie', "''", ',', 'taylor', 'i', 'can', 'read', 'you', 'like', 'a', 'magazine', ',', 'taylor', '``', 'ai', "n't", 'it', 'funny', ',', 'rumors', ',', 'lie', "''", ',', 'taylor', 'and', 'i', 'know', 'you', 'heard', 'about', 'me', ',', 'taylor', '``', 'so', 'hey', ',', 'let', "'s", 'be', 'friends', "''", ',', 'taylor', 'i', "'m", 'dying', 'to', 'see', 'how', 'this', 'one', 'ends', ',', 'taylor', 'grab', 'y

In [7]:
model = Word2Vec(tokens,vector_size=400)

In [8]:
model.wv.key_to_index

{',': 0,
 '``': 1,
 'taylor': 2,
 "''": 3,
 'shakes': 4,
 'the': 5,
 'i': 6,
 'and': 7,
 'you': 8,
 'to': 9,
 'of': 10,
 "'s": 11,
 'a': 12,
 'that': 13,
 'in': 14,
 'my': 15,
 'is': 16,
 'it': 17,
 ';': 18,
 'but': 19,
 'be': 20,
 'we': 21,
 'on': 22,
 "n't": 23,
 'me': 24,
 'love': 25,
 'do': 26,
 'like': 27,
 'shake': 28,
 'with': 29,
 'your': 30,
 'all': 31,
 '.': 32,
 'this': 33,
 'for': 34,
 'so': 35,
 'not': 36,
 '?': 37,
 "'d": 38,
 "'ll": 39,
 'as': 40,
 "'m": 41,
 "'": 42,
 'mmm': 43,
 'what': 44,
 'can': 45,
 'when': 46,
 'know': 47,
 'his': 48,
 'see': 49,
 'got': 50,
 'go': 51,
 'or': 52,
 'just': 53,
 'from': 54,
 'no': 55,
 'there': 56,
 'gon': 57,
 'na': 58,
 'say': 59,
 'he': 60,
 ':': 61,
 'make': 62,
 'which': 63,
 'up': 64,
 'out': 65,
 'take': 66,
 'thou': 67,
 'more': 68,
 'they': 69,
 'our': 70,
 'was': 71,
 'if': 72,
 'never': 73,
 'their': 74,
 "'re": 75,
 'have': 76,
 'are': 77,
 'said': 78,
 'could': 79,
 'play': 80,
 'were': 81,
 'fair': 82,
 'eyes': 83,
 'b

In [9]:
model.wv.get_vector("love", norm=True)

array([-0.01244316, -0.00474818, -0.00226204,  0.07110666, -0.01293106,
       -0.05858142,  0.01537734,  0.04405263,  0.00846672,  0.04501512,
       -0.03430844, -0.05251516, -0.00454302,  0.02986043,  0.00792217,
       -0.0402973 , -0.06446647,  0.04706138, -0.01737349, -0.10458827,
        0.04513253, -0.0209356 , -0.00444568,  0.01638206, -0.0236436 ,
        0.0581891 , -0.0251887 , -0.03999691, -0.09759444,  0.00049621,
        0.07086493, -0.02136696,  0.07312963, -0.00674354, -0.08552502,
        0.01412842,  0.0585466 , -0.04093691, -0.01351422, -0.06974103,
       -0.09837921,  0.02411548, -0.05792809, -0.05431444,  0.07759665,
       -0.06264051,  0.03448279, -0.01006333,  0.05433099,  0.0624646 ,
        0.02363323, -0.01816585, -0.02740839, -0.06264055,  0.08153925,
       -0.05015216, -0.01850825, -0.00759975, -0.06680286,  0.0099658 ,
       -0.01194362, -0.02522598,  0.00268466, -0.05520289, -0.11807021,
        0.01811071, -0.06527038,  0.09138719, -0.07361459,  0.16

In [10]:
model.wv.most_similar('love')

[(',', 0.9992855787277222),
 ('the', 0.9991974234580994),
 ("''", 0.9991714954376221),
 ('``', 0.9991647601127625),
 ('shakes', 0.9991487264633179),
 ('and', 0.9991065859794617),
 ('taylor', 0.9990973472595215),
 ('you', 0.9990931749343872),
 ('i', 0.999040961265564),
 ('that', 0.9990392327308655)]

In [22]:
model.wv.get_vector("baby", norm=True)

array([-0.01163442, -0.00149913, -0.0062196 ,  0.07109404, -0.01360983,
       -0.05484423,  0.01330073,  0.05002466,  0.00992617,  0.04046572,
       -0.03064542, -0.05187479, -0.00519226,  0.02947073,  0.00654973,
       -0.04217781, -0.07082838,  0.04107527, -0.02143601, -0.10036758,
        0.044134  , -0.02101821, -0.00419646,  0.02028404, -0.0242014 ,
        0.0527554 , -0.02410161, -0.03896075, -0.09993555, -0.00108917,
        0.07298011, -0.02018335,  0.07049435, -0.01288289, -0.08924879,
        0.0139113 ,  0.05784003, -0.03907659, -0.01853936, -0.07200664,
       -0.09712283,  0.02263428, -0.05554783, -0.05372822,  0.07747141,
       -0.06852892,  0.0348012 , -0.00391475,  0.05883604,  0.05979948,
        0.02888854, -0.01707758, -0.02782644, -0.06285546,  0.07825546,
       -0.0461849 , -0.01516677, -0.0037682 , -0.06498522,  0.01018276,
       -0.01341166, -0.02402634,  0.00039991, -0.05984943, -0.11706498,
        0.02168069, -0.06165081,  0.08863923, -0.07090677,  0.16

In [12]:
model.wv.most_similar('baby')

[(',', 0.9985888004302979),
 ('the', 0.9984907507896423),
 ("''", 0.9984638094902039),
 ('``', 0.9984490871429443),
 ('taylor', 0.9984366297721863),
 ('you', 0.9984309077262878),
 ('i', 0.9984195828437805),
 ('shakes', 0.9984118938446045),
 ('and', 0.998359203338623),
 ('a', 0.9983288645744324)]

In [14]:
model.wv.similarity('will', 'love')

0.9962447

In [30]:
model.wv.similarity('taylor', 'love')

0.9990973

In [15]:
model.wv.similarity('baby', 'love')

0.99791527

In [20]:
model.wv.similarity('thou', 'taylor')

0.9985268

In [23]:
model.wv.get_vector("hate", norm=True)

array([-1.37987863e-02, -2.58264551e-03,  3.41834209e-04,  7.04631135e-02,
       -1.40270311e-02, -5.94077446e-02,  1.76857859e-02,  4.85377163e-02,
        1.15830153e-02,  4.75967340e-02, -3.45395096e-02, -5.68195358e-02,
       -3.97316646e-03,  2.78746709e-02,  5.82332630e-03, -4.27201129e-02,
       -7.07092360e-02,  4.53368239e-02, -1.76689010e-02, -1.03365928e-01,
        4.46406528e-02, -2.23226324e-02, -2.83306884e-03,  1.64264217e-02,
       -2.47545317e-02,  5.77206276e-02, -2.38405243e-02, -4.06019576e-02,
       -1.01155572e-01,  6.07350934e-03,  7.26282299e-02, -2.17171125e-02,
        7.35199526e-02, -1.08701093e-02, -8.56019631e-02,  1.15968399e-02,
        5.95839806e-02, -4.11794558e-02, -1.02721006e-02, -6.91789985e-02,
       -1.02114886e-01,  2.07576547e-02, -5.50272837e-02, -5.59224673e-02,
        7.76021630e-02, -6.81997612e-02,  3.16179208e-02, -4.62121470e-03,
        5.85112758e-02,  6.31545112e-02,  2.54274867e-02, -2.17810702e-02,
       -3.03411409e-02, -

In [26]:
model.wv.similarity('thou', 'baby')

0.9972226

In [27]:
model.wv.similarity('thou', 'mmm')

0.99817157

In [32]:
model.wv.similarity('will', 'thou')

0.99591875

In [33]:
model.wv.most_similar('taylor')

[(',', 0.9997791051864624),
 ("''", 0.9996920824050903),
 ('``', 0.9996811151504517),
 ('the', 0.9996777176856995),
 ('you', 0.9996488094329834),
 ('shakes', 0.999617338180542),
 ('and', 0.999591588973999),
 ('i', 0.9995555281639099),
 ('that', 0.9995548725128174),
 ('a', 0.9995308518409729)]

In [34]:
model.wv.most_similar('fake')

[(',', 0.9980595707893372),
 ('the', 0.9980000853538513),
 ('``', 0.9979833364486694),
 ("''", 0.9979669451713562),
 ('you', 0.9979196190834045),
 ('shakes', 0.997901439666748),
 ('that', 0.9978917837142944),
 ('taylor', 0.9978893995285034),
 ('i', 0.9978635907173157),
 ('but', 0.9978451728820801)]

In [35]:
model.wv.most_similar('people')

[('``', 0.9978945255279541),
 (',', 0.9978510737419128),
 ('shakes', 0.9977887272834778),
 ('taylor', 0.9977452754974365),
 ("''", 0.9977203607559204),
 ('the', 0.9976797103881836),
 ('i', 0.9976478219032288),
 ('a', 0.9976374506950378),
 ('mmm', 0.9976281523704529),
 ('you', 0.9976206421852112)]

In [38]:
model.wv.most_similar('her')

[(',', 0.998116672039032),
 ('``', 0.998040497303009),
 ('and', 0.9980130195617676),
 ('you', 0.9980091452598572),
 ("''", 0.9979930520057678),
 ('the', 0.9979685544967651),
 ('taylor', 0.9979426860809326),
 ('i', 0.9978976249694824),
 ('that', 0.997887909412384),
 ('shakes', 0.9978725910186768)]

In [40]:
model.wv.most_similar('his')

[(',', 0.9982366561889648),
 ('``', 0.9982103705406189),
 ('shakes', 0.9982041716575623),
 ("''", 0.9981958866119385),
 ('taylor', 0.9981184005737305),
 ('and', 0.998102605342865),
 ('the', 0.9980757832527161),
 ('you', 0.9980562329292297),
 ('i', 0.9979768395423889),
 ('a', 0.9979667067527771)]

In [46]:
model.wv.most_similar('their')

[(',', 0.9991352558135986),
 ('``', 0.9990623593330383),
 ('shakes', 0.9990174770355225),
 ("''", 0.9990147352218628),
 ('the', 0.9989834427833557),
 ('and', 0.9989603757858276),
 ('taylor', 0.9989443421363831),
 ('you', 0.9989287257194519),
 ('i', 0.9989184141159058),
 ("'s", 0.9988483190536499)]

In [48]:
model.wv.most_similar('play')

[(',', 0.9980928301811218),
 ('the', 0.9979978203773499),
 ("''", 0.9979841113090515),
 ('taylor', 0.9979763031005859),
 ('you', 0.9979591965675354),
 ('and', 0.9979342222213745),
 ('``', 0.9978725910186768),
 ('but', 0.9978664517402649),
 ('i', 0.9978252053260803),
 ('to', 0.9978216290473938)]