<a href="https://colab.research.google.com/github/BFCC/BFCC.github.io/blob/main/wiLLMs_revised.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import re
import nltk
import numpy as np
import matplotlib.pyplot as plt
import random

from gensim.models import Word2Vec

from sklearn.decomposition import IncrementalPCA
from sklearn.manifold import TSNE

In [8]:
file = open("input.txt", 'r').read()

In [9]:
for char in ["\n", "\r", "\d", "\t"]:
    file = file.replace(char, " ")

In [10]:
print(file[:100])

First Citizen: Before we proceed any further, hear me speak.  All: Speak, speak.  First Citizen: You


In [11]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [12]:
def sample_clean_text(text: str):
    # step 1: tokenize the text into sentences
    sentences = nltk.sent_tokenize(text)

    # step 2: tokenize each sentence into words
    tokenized_sentences = [nltk.word_tokenize(sent) for sent in sentences]

    # step 3: convert each word to lowercase
    tokenized_text = [[word.lower() for word in sent] for sent in tokenized_sentences]

    # return your tokens
    return tokenized_text

# call the function
tokens = sample_clean_text(text = file)

# check
print(tokens[:10])

[['first', 'citizen', ':', 'before', 'we', 'proceed', 'any', 'further', ',', 'hear', 'me', 'speak', '.'], ['all', ':', 'speak', ',', 'speak', '.'], ['first', 'citizen', ':', 'you', 'are', 'all', 'resolved', 'rather', 'to', 'die', 'than', 'to', 'famish', '?'], ['all', ':', 'resolved', '.'], ['resolved', '.'], ['first', 'citizen', ':', 'first', ',', 'you', 'know', 'caius', 'marcius', 'is', 'chief', 'enemy', 'to', 'the', 'people', '.'], ['all', ':', 'we', "know't", ',', 'we', "know't", '.'], ['first', 'citizen', ':', 'let', 'us', 'kill', 'him', ',', 'and', 'we', "'ll", 'have', 'corn', 'at', 'our', 'own', 'price', '.'], ["is't", 'a', 'verdict', '?'], ['all', ':', 'no', 'more', 'talking', 'o', "n't", ';', 'let', 'it', 'be', 'done', ':', 'away', ',', 'away', '!']]


In [13]:
model = Word2Vec(tokens,vector_size=100)

In [14]:
model.wv.key_to_index

{',': 0,
 ':': 1,
 '.': 2,
 'the': 3,
 'and': 4,
 'i': 5,
 'to': 6,
 'of': 7,
 ';': 8,
 'you': 9,
 'my': 10,
 'a': 11,
 'that': 12,
 '?': 13,
 'is': 14,
 'in': 15,
 'not': 16,
 '!': 17,
 'for': 18,
 "'s": 19,
 'with': 20,
 'it': 21,
 'me': 22,
 'be': 23,
 'your': 24,
 'he': 25,
 'his': 26,
 'but': 27,
 'this': 28,
 'have': 29,
 "'d": 30,
 'as': 31,
 'thou': 32,
 'him': 33,
 'what': 34,
 'so': 35,
 'thy': 36,
 'will': 37,
 'we': 38,
 'king': 39,
 'no': 40,
 'by': 41,
 'all': 42,
 'shall': 43,
 'her': 44,
 'if': 45,
 'our': 46,
 'are': 47,
 'do': 48,
 'thee': 49,
 'lord': 50,
 'now': 51,
 'o': 52,
 'on': 53,
 'good': 54,
 "'": 55,
 'from': 56,
 'come': 57,
 'sir': 58,
 'or': 59,
 'which': 60,
 'more': 61,
 'was': 62,
 "'ll": 63,
 'then': 64,
 'here': 65,
 'at': 66,
 'they': 67,
 'she': 68,
 'would': 69,
 'let': 70,
 'how': 71,
 'well': 72,
 'than': 73,
 'their': 74,
 'them': 75,
 'duke': 76,
 'can': 77,
 'am': 78,
 'hath': 79,
 '--': 80,
 'say': 81,
 'there': 82,
 'when': 83,
 'one': 84,

In [49]:
model.wv.get_vector("kate", norm=True)

array([-0.01933577,  0.04677144,  0.01654928,  0.11584157,  0.10374434,
       -0.30219635,  0.07282429,  0.333535  , -0.07287282, -0.0450923 ,
        0.01519664, -0.17196772, -0.00907077,  0.04084505, -0.04892579,
       -0.11243871,  0.07600474, -0.04960907, -0.00966576, -0.22862326,
        0.08918396,  0.02511481,  0.07456524, -0.05168753,  0.07903016,
       -0.01158264, -0.10044956, -0.04230422, -0.13498864,  0.0388631 ,
        0.12204558,  0.07849641,  0.13193488, -0.11378178, -0.03126972,
        0.15226965,  0.05695671, -0.11478041, -0.02356885, -0.22255658,
        0.06438415, -0.17008913, -0.01160255, -0.03771301,  0.04847882,
        0.0380516 , -0.08595534,  0.04989558,  0.06525116,  0.02173018,
        0.07205766, -0.14796789, -0.02568386,  0.00508823, -0.05074114,
        0.10482439,  0.13693361,  0.06373763, -0.10777524,  0.03807615,
       -0.02456915, -0.02029794,  0.04356632, -0.07573704, -0.10573927,
        0.15015425,  0.14240552,  0.1055517 , -0.26315078,  0.14

In [50]:
model.wv.most_similar('kate')

[('gentlemen', 0.9930965900421143),
 ('hie', 0.992615818977356),
 ('commend', 0.9907503128051758),
 ('knock', 0.9905545115470886),
 ('masters', 0.9894234538078308),
 ('worship', 0.989274799823761),
 ('morrow', 0.9891580939292908),
 ('sirrah', 0.9889315962791443),
 ('signior', 0.9887718558311462),
 ('plain', 0.9885265827178955)]

In [51]:
model.wv.similarity('eat', 'kate')

0.9703561

In [52]:
model.wv.similarity('nay', 'kate')

0.9330069

In [55]:
model.wv.similarity('womb', 'kate')

0.91203475

In [56]:
model.wv.similarity('shrew', 'kate')

0.9087301

In [57]:
model.wv.similarity('tame', 'kate')

0.97108674

In [64]:
model.wv.similarity('katharina', 'kate')

0.94100547

In [65]:
model.wv.similarity('king', 'kate')

0.57366985

In [66]:
model.wv.similarity('france', 'kate')

0.9035554

In [68]:
model.wv.similarity('harry', 'kate')

0.94995624

In [69]:
model.wv.similarity('will', 'kate')

0.7142572

In [72]:
model.wv.similarity('sit', 'kate')

0.9875739

In [73]:
model.wv.similarity('wedding', 'kate')

0.9175848

In [31]:
model.wv.get_vector("bianca", norm=True)

array([-0.013897  ,  0.06911439,  0.03799673,  0.09710885,  0.09491027,
       -0.2975235 ,  0.07295135,  0.32855797, -0.06786937, -0.04132128,
       -0.0027887 , -0.16070658, -0.01161983,  0.0238074 , -0.05335452,
       -0.10364833,  0.09923995, -0.06705429, -0.02266516, -0.23659079,
        0.10451613,  0.04141106,  0.06450705, -0.03070183,  0.06494054,
        0.00325652, -0.12181978, -0.04878669, -0.11696023,  0.0575088 ,
        0.15632924,  0.07651882,  0.0943197 , -0.12540092, -0.03826957,
        0.17109767,  0.09557673, -0.09632498, -0.04886787, -0.22956973,
        0.05689729, -0.16873643, -0.02049764, -0.05379177,  0.03197764,
        0.04141934, -0.0603533 ,  0.05147323,  0.08935328,  0.04211857,
        0.06455295, -0.13138111, -0.0310388 ,  0.00863762, -0.0884776 ,
        0.13087302,  0.1335202 ,  0.07398657, -0.12433005,  0.03587458,
       -0.01808414,  0.00348294,  0.0438596 , -0.05486177, -0.08351772,
        0.14747645,  0.13014035,  0.09288564, -0.26509133,  0.13

In [32]:
model.wv.most_similar('bianca')

[('paris', 0.9961642026901245),
 ('faith', 0.9954509139060974),
 ('thursday', 0.9947230815887451),
 ('oxford', 0.9947035908699036),
 ('marcius', 0.9943558573722839),
 ('plain', 0.9939066171646118),
 ('return', 0.9937164783477783),
 ('courage', 0.9936020970344543),
 ('amen', 0.993006706237793),
 ('roman', 0.9929357171058655)]

In [ ]:
 feature of how infrequently 'bianca' appears in this corpus?

honestly makes no sense to me, neither 'paris' 'oxford' 'marcius' nor 'roman' appear in the two plays in which 'bianca' features.

In [34]:
model.wv.similarity('bianca', 'virtue')

0.95254445

In [35]:
model.wv.similarity('bianca', 'kate')

0.98759466

In [38]:
model.wv.similarity('bianca', 'england')

0.93199825

In [43]:
model.wv.similarity('bianca', 'master')

0.9665985

In [45]:
model.wv.similarity('bianca', 'government')

0.95105904

In [46]:
model.wv.similarity('bianca', 'justice')

0.9760213

In [47]:
model.wv.similarity('bianca', 'juliet')

0.92828006

In [74]:
model.wv.similarity('bianca', 'wedding')

0.938393

In [30]:
model.wv.get_vector("will", norm=True)

array([ 7.77228782e-03, -2.54198741e-02,  3.42907012e-02,  2.10436210e-02,
        1.48924336e-01, -3.57080013e-01,  9.39758569e-02,  1.51385769e-01,
       -9.02223401e-03, -3.41961952e-03,  1.17266074e-01, -1.67099029e-01,
        7.27848187e-02,  9.14903283e-02, -1.14405714e-01, -6.10986538e-03,
       -1.65246818e-02, -6.63282350e-02,  5.48732318e-02, -1.78070888e-01,
       -3.38233449e-03,  2.77224425e-02,  4.25567254e-02, -7.54639134e-02,
        1.01384655e-01,  7.57525042e-02, -3.37273441e-02,  6.03311360e-02,
       -1.22360781e-01, -5.22072352e-02,  4.27334122e-02,  7.20910504e-02,
        1.95981547e-01, -8.83398503e-02, -9.02782604e-02, -8.89194235e-02,
       -5.02326526e-02, -1.86838791e-01, -7.70373940e-02, -1.16125032e-01,
       -1.18996367e-01, -1.10732086e-01,  1.03017632e-02, -8.87077302e-03,
        7.45778009e-02,  6.56640381e-02, -1.41245306e-01,  7.30385482e-02,
       -5.77683672e-02, -1.53390858e-02,  2.63901614e-02, -9.80534106e-02,
       -9.82407182e-02,  

In [16]:
model.wv.most_similar('will')

[('shall', 0.9795094132423401),
 ("'ll", 0.9697742462158203),
 ('may', 0.9644275903701782),
 ('must', 0.9554563760757446),
 ('should', 0.9218795895576477),
 ('can', 0.9203559160232544),
 ('see', 0.9109951257705688),
 ('did', 0.910571813583374),
 ('do', 0.90828937292099),
 ('have', 0.9037193059921265)]

In [33]:
model.wv.similarity('will', 'increase')

0.6769038

In [18]:
model.wv.similarity('will', 'desire')

0.77950066

In [19]:
model.wv.similarity('will', 'wish')

0.8620475

In [20]:
model.wv.similarity('will', 'cease')

0.7071471

In [21]:
model.wv.similarity('will', 'sea')

0.6508622

In [22]:
model.wv.similarity('will', 'die')

0.7804762